In [1]:
import numpy as np
from numpy.random import randint as ri
a=ri(1,99,30)
a

array([37, 48, 67, 85, 96, 62, 32, 22, 23, 35, 98, 87, 41, 82, 30, 71, 72,
       68, 14, 17, 84, 35, 34, 93, 12, 19, 85, 79, 43, 65])

In [2]:
b=a.reshape(2,3,5)
b

array([[[37, 48, 67, 85, 96],
        [62, 32, 22, 23, 35],
        [98, 87, 41, 82, 30]],

       [[71, 72, 68, 14, 17],
        [84, 35, 34, 93, 12],
        [19, 85, 79, 43, 65]]])

In [3]:
c=a.reshape(6,5)
c

array([[37, 48, 67, 85, 96],
       [62, 32, 22, 23, 35],
       [98, 87, 41, 82, 30],
       [71, 72, 68, 14, 17],
       [84, 35, 34, 93, 12],
       [19, 85, 79, 43, 65]])

In [5]:
print("Min. of a:",c.min())
print("Max. of b:",c.max())

Min. of a: 12
Max. of b: 98


In [7]:
np.mean(c)

54.53333333333333

In [9]:
m=ri(1,100,25).reshape(5,5)
print("\n 5x5 Matrix of random integers\n",'-'*50, "\n",m)
print("\n Here is the sorted matrix along each row\n",'-'*50,"\n",np.sort(m))   #Default axis=1


 5x5 Matrix of random integers
 -------------------------------------------------- 
 [[64 38 75 33 90]
 [59 39  6 14 57]
 [ 3 17 57 54 58]
 [ 1 44 37 89 17]
 [14 68 29 53  9]]

 Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[33 38 64 75 90]
 [ 6 14 39 57 59]
 [ 3 17 54 57 58]
 [ 1 17 37 44 89]
 [ 9 14 29 53 68]]


In [10]:
print("\n Here is the sorted matrix along each column \n",'-'*50,"\n",np.sort(m,axis=0))


 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[ 1 17  6 14  9]
 [ 3 38 29 33 17]
 [14 39 37 53 57]
 [59 44 57 54 58]
 [64 68 75 89 90]]


In [11]:
arr=np.arange(13,30)
print("Array:",arr)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [12]:
print("Elements at the 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:",arr[3:6])

Elements at the 7th index is: 20
Elements from 3rd to 5th index are: [16 17 18]


In [1]:
print('Original Matrix \n\n',mat)  #update matrix

NameError: name 'mat' is not defined

In [2]:
mat[0,1]=35
print(mat)

NameError: name 'mat' is not defined

In [3]:
mat[1,0]=100
print[mat]

NameError: name 'mat' is not defined

In [4]:
mat=np.array(ri(10,100,15))
print("Matrix of random 2-digit numbers\n-------------------------------------\n",mat)
xyz=mat[mat>70]
xyz

NameError: name 'np' is not defined

In [6]:
array([92,94,77,78])
print("Elements greaterthan 50\n", mat[mat>50])
mat>50
print(np.where(mat==50))

NameError: name 'array' is not defined