In [3]:
import numpy as np
np.sqrt(2)

1.4142135623730951

In [5]:
print('Minimum',np.min([25, 30, 57, 18]))

Minimum 18


In [7]:
print('Maximum',np.max([25, 30, 57, 18]))

Maximum 57


In [8]:
np.ceil(29.5)

30.0

In [9]:
np.ceil(np.sqrt(10))

4.0

In [10]:
np.array([5,9,14])

array([ 5,  9, 14])

In [11]:
type([5,9,14])

list

In [5]:
a=np.array([1,2], [3,4], [4,5]) ##
print ("Type - ", a.dtype)
print('\n','*'*30)
print('\n'a)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [14]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [8]:
np.array(np.mat('1 2 3; 3 4 5'))
array([1, 2, 3], [3, 4, 5])

NameError: name 'array' is not defined

In [17]:
a=[1, 2]
c=np.array(a)
print (c)

[1 2]


In [18]:
b=np.asarray(c)  #copies array into another
print (b)

[1 2]


In [21]:
my_mat=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat=np.array(my_mat)
print ("Type/class of this object:" , type(mat))
#print("Here is the matrix \n--------\n" mat,"\n--------\n")
print("Dimension of this matrix: ", mat.ndim, sep='')
print("shape of this matrix:", mat.shape)
print("Size of this matrix:", mat.size, sep='')
print("Date type of this matrix:", mat.dtype)

Type/class of this object: <class 'numpy.ndarray'>
Dimension of this matrix: 2
shape of this matrix: (3, 3)
Size of this matrix:9
Date type of this matrix: int32


In [24]:
list(range(2,10.5,.4))

TypeError: 'float' object cannot be interpreted as an integer

In [25]:
a=np.arange((2,10.5,.4))
a

TypeError: arange: scalar arguments expected instead of a tuple.

In [26]:
a[::-1]  #Reverse order

NameError: name 'a' is not defined

In [18]:
print ("Every 5th number from 50 in reverse order\n", np.arange)

Every 5th number from 50 in reverse order
 <built-in function arange>


In [31]:
print ("Linearly spaced numbers between 1 and 5\n-------------------------") #Linearly spaced data
print(np.linspace(10, 40, 5))

Linearly spaced numbers between 1 and 5
-------------------------
[10.  17.5 25.  32.5 40. ]


In [14]:
np.linspace(2.0, 3.0, num=4, endpoint=False, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [12]:
np.linspace(2.0, 3.0, num=4, endpoint=True, retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [13]:
print(np.linspace(4.5678,25.9865,39,retstep=True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), 0.56365)


In [27]:
print("Vector of zeroes\n------------------")
print(np.zeros(5))

Vector of zeroes
------------------
[0. 0. 0. 0. 0.]


In [38]:
print("Matrix of zeroes\n-------------")
print(np.zeros((5,6)))   #Notice Tuples

Matrix of zeroes
-------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [40]:
print("Matrix of ones\n------------------")
print(np.ones((5,8))) #Matrix dimension specified by Tuples

Matrix of ones
------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
print("Matrix of 5's\n------------------")
print(5*np.ones((2,3)))

Matrix of 5's
------------------
[[5. 5. 5.]
 [5. 5. 5.]]


In [36]:
x=np.arange(30).reshape(10,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [37]:
x=np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])