In [4]:
import numpy as np
np.sqrt(2)

1.4142135623730951

In [5]:
print('Minimum',np.min([25, 30, 57, 18]))

Minimum 18


In [7]:
print('Maximum',np.max([25, 30, 57, 18]))

Maximum 57


In [8]:
np.ceil(29.5)

30.0

In [9]:
np.ceil(np.sqrt(10))

4.0

In [10]:
np.array([5,9,14])

array([ 5,  9, 14])

In [11]:
type([5,9,14])

list

In [13]:
a=np.array([1,2], [3,4], [4,5])
print ("Type - ", a.dtype)
print('\n','*'*30)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [14]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [15]:
np.array(np.mat('1 2 3; 3 4 5'))
array([[1, 2, 3], [3, 4, 5]])

NameError: name 'array' is not defined

In [17]:
a=[1, 2]
c=np.array(a)
print (c)

[1 2]


In [18]:
b=np.asarray(c)  #copies array into another
print (b)

[1 2]


In [21]:
my_mat=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat=np.array(my_mat)
print ("Type/class of this object:" , type(mat))
#print("Here is the matrix \n--------\n" mat,"\n--------\n")
print("Dimension of this matrix: ", mat.ndim, sep='')
print("shape of this matrix:", mat.shape)
print("Size of this matrix:", mat.size, sep='')
print("Date type of this matrix:", mat.dtype)

Type/class of this object: <class 'numpy.ndarray'>
Dimension of this matrix: 2
shape of this matrix: (3, 3)
Size of this matrix:9
Date type of this matrix: int32


In [23]:
list (range(2,10.5,.4))

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
a=np.arange((2,10.5,0.4))
a

TypeError: arange: scalar arguments expected instead of a tuple.

In [28]:
a[ : :-1]  #Reverse order

[2, 1]

In [29]:
print ("Every 5th number from 50 in reverse order\n", np.arange)

Every 5th number from 50 in reverse order
 <built-in function arange>


In [31]:
print ("Linearly spaced numbers between 1 and 5\n-------------------------") #Linearly spaced data
print(np.linspace(10, 40, 5))

Linearly spaced numbers between 1 and 5
-------------------------
[10.  17.5 25.  32.5 40. ]


In [34]:
np.linspace(2.0, 3.0, num=4, endpoint=False, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [ ]:
print(np.linspace(4.5678,25.9865,39,retstep=True))