In [3]:
import numpy as np

In [5]:
np.random.seed(6)
print("Random number generation(from Uniform distribution)")
print(np.random.rand(10,6))

Random number generation(from Uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [7]:
print("Number from Normal distribution with zero mean and standard deviation 1, i.e., Standard normal")
print(np.random.randn(10,3))

Number from Normal distribution with zero mean and standard deviation 1, i.e., Standard normal
[[-2.12647459  0.75144883 -0.54060704]
 [ 0.79322236  0.17365335 -1.03543429]
 [ 0.87426839 -0.73957208  0.52294535]
 [-0.59187648 -0.47748711  0.11252968]
 [ 1.90474232  0.69415315 -0.01958134]
 [ 1.66284285  0.03060843 -0.29749921]
 [-0.96813764  0.16706673  0.11660197]
 [-0.68225732 -1.91402115 -0.13990231]
 [ 0.11492459 -0.39500464 -0.95331626]
 [-1.07282736 -0.48444561  1.36293786]]


In [9]:
print("Random integer vector:", np.random.(5,20,10))    
#randint(low,high)

SyntaxError: invalid syntax (Temp/ipykernel_7928/3847420055.py, line 1)

In [10]:
print("\n Random integer matrix")
print(np.randint(1,30,(6,7)))


 Random integer matrix


AttributeError: module 'numpy' has no attribute 'randint'

In [11]:
emp_salary=np.random.randint(8,70,10)  #Numpy comdition
emp_salary

array([10, 20, 57, 55, 22, 68, 38, 34, 49, 58])

In [12]:
np.clip(emp_salary,a_min=20,a_max=50)

array([20, 20, 50, 50, 22, 50, 38, 34, 49, 50])

In [15]:
#np.where gives index details  This is a condition which here is helping to find actual salary which is less than or greater than some salary

print(np.where(emp_salary<20))  

(array([0], dtype=int64),)
