In [4]:
import numpy as np 
from numpy.random import randint as ri

In [8]:
mat1=np.array(ri(1,10,9)).reshape(3,3)   #Universal Functions
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrix of random single digit numbers\n", mat1)
print("\n 2nd Matrix of random single digit numbers\n", mat2)


 1st Matrix of random single digit numbers
 [[7 6 4]
 [2 2 5]
 [5 4 2]]

 2nd Matrix of random single digit numbers
 [[9 9 8]
 [6 3 6]
 [6 7 4]]


In [6]:
print("\n Addition\n-----------------\n",mat1+mat2)
print("\n Multiplication\n------------------\n",mat1*mat2)


 Addition
-----------------
 [[16 10 12]
 [15  4 13]
 [11  8  7]]

 Multiplication
------------------
 [[64 21 32]
 [54  4 42]
 [18 16 10]]


In [9]:
print('mat1=\n',mat1)
print('mat2=\n',mat2)

mat1=
 [[7 6 4]
 [2 2 5]
 [5 4 2]]
mat2=
 [[9 9 8]
 [6 3 6]
 [6 7 4]]


In [10]:
print("\n Division \n-------------------\n",mat1/mat2)
print("\n Linear combination:3*A-2*B \n--------------------\n",3*mat1-2*mat2)


 Division 
-------------------
 [[0.77777778 0.66666667 0.5       ]
 [0.33333333 0.66666667 0.83333333]
 [0.83333333 0.57142857 0.5       ]]

 Linear combination:3*A-2*B 
--------------------
 [[ 3  0 -4]
 [-6  0  3]
 [ 3 -2 -2]]
